import { useState } from 'react';

/**
 * Reusable controlled form for creating or editing a teacher.
 *
 * Create mode: asks for Name, Email, Phone only.
 *   — Employee ID is auto-generated by the backend.
 *   — Temporary password is emailed automatically.
 *
 * Edit mode: asks for Name, Phone, Employee ID (all optional).
 *
 * Props:
 *   initialData  — teacher doc (populated) for edit mode; null for create
 *   onSubmit     — (formData: object) => void
 *   loading      — boolean
 *   apiErrors    — { [field]: message } — 422 errors from API
 */
export default function TeacherForm({
  initialData = null,
  onSubmit,
  loading = false,
  apiErrors = {},
}) {
  const isEdit = !!initialData;

  const [form, setForm] = useState({
    name: initialData?.userId?.name ?? '',
    email: initialData?.userId?.email ?? '',
    phone: initialData?.userId?.phone ?? '',
    employeeId: initialData?.employeeId ?? '',
  });

  const [localErrors, setLocalErrors] = useState({});
  const allErrors = { ...localErrors, ...apiErrors };

  const set = (field) => (e) =>
    setForm((prev) => ({ ...prev, [field]: e.target.value }));

  const validate = () => {
    const errs = {};
    if (!form.name.trim()) errs.name = 'Name is required';
    if (!isEdit && !form.email.trim()) errs.email = 'Email is required';
    setLocalErrors(errs);
    return Object.keys(errs).length === 0;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!validate()) return;
    const payload = { name: form.name.trim(), phone: form.phone.trim() || undefined };
    if (!isEdit) {
      payload.email = form.email.trim();
    }
    if (isEdit && form.employeeId.trim()) {
      payload.employeeId = form.employeeId.trim().toUpperCase();
    }
    onSubmit(payload);
  };

  return (
    <form onSubmit={handleSubmit} noValidate autoComplete="off" className="space-y-4">
      {/* Name */}
      <Field label="Full Name" error={allErrors.name} required>
        <input
          type="text"
          value={form.name}
          onChange={set('name')}
          placeholder="e.g. Mr Ahmed Ali"
          className={inputCls(allErrors.name)}
        />
      </Field>

      {/* Email — create only */}
      {!isEdit && (
        <Field label="Email Address" error={allErrors.email} required>
          <input
            type="email"
            value={form.email}
            onChange={set('email')}
            placeholder="teacher@school.com"
            autoComplete="off"
            className={inputCls(allErrors.email)}
          />
          <p className="text-xs text-gray-400 mt-1">
            A temporary login password will be emailed to this address.
          </p>
        </Field>
      )}

      {/* Phone */}
      <Field label="Phone" error={allErrors.phone}>
        <input
          type="tel"
          value={form.phone}
          onChange={set('phone')}
          placeholder="Optional"
          className={inputCls(allErrors.phone)}
        />
      </Field>

      {/* Employee ID — edit only (read-only hint in create) */}
      {isEdit ? (
        <Field label="Employee ID" error={allErrors.employeeId}>
          <input
            type="text"
            value={form.employeeId}
            onChange={set('employeeId')}
            placeholder="e.g. TCH-001"
            className={inputCls(allErrors.employeeId)}
          />
        </Field>
      ) : (
        <p className="text-xs text-indigo-600 bg-indigo-50 border border-indigo-100 rounded-lg px-3 py-2">
          Employee ID will be auto-assigned (e.g. TCH-001).
        </p>
      )}

      <button
        type="submit"
        disabled={loading}
        className="w-full py-2.5 rounded-xl bg-indigo-600 text-white text-sm font-semibold hover:bg-indigo-700 disabled:opacity-50 transition"
      >
        {loading ? 'Saving…' : isEdit ? 'Update Teacher' : 'Add Teacher'}
      </button>
    </form>
  );
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function Field({ label, error, required, children }) {
  return (
    <div>
      <label className="block text-xs font-medium text-gray-600 mb-1">
        {label}
        {required && <span className="text-red-500 ml-0.5">*</span>}
      </label>
      {children}
      {error && <p className="text-xs text-red-600 mt-1">{error}</p>}
    </div>
  );
}

const inputCls = (error) =>
  `w-full rounded-lg border px-3 py-2 text-sm outline-none transition focus:ring-2 focus:ring-indigo-300 ${
    error ? 'border-red-400 bg-red-50' : 'border-gray-200 bg-white focus:border-indigo-400'
  }`;
